// SPEC §17.8 — Multi-host fan-out from a Task Offer.
//
// The merge point between two NeoProtocol planes:
//   • §6/§7  — Originator decomposes a NL prompt into a JSON
//              Task Offer with channels + reducers + edges
//   • §16/§17 — two Coworkers share a Y.Doc + ACP channel over P2P
//
// What §17.8 adds:
//   • The Task Offer is broadcast through the Workspace channel
//     (Y.Map "task") so every Coworker sees the same graph
//   • Each leaf node deterministically maps to ONE Coworker by
//     `sort(client_ids)[hash(leaf_id) % N]` — both peers compute the
//     SAME assignment with no coordination round-trip
//   • Each peer runs only its assigned leaves, using its currently
//     selected agent (BYOK / Local / Mock); results land in shared
//     Y.Map channels with attribution metadata
//   • The reducer (also assigned by the same hash) waits for its
//     `reads` channels, computes the output, writes the final
//     `report` channel, and prepends the markdown report to the
//     workspace document with §17.5 attribution
//
// Why deterministic assignment beats coordination:
//   • Y.js CRDT means there is no global "who claims this leaf?"
//     primitive. Naïve claim would race; deterministic hash is
//     race-free by construction.
//   • Both peers reach the same conclusion the moment they observe
//     the offer + the channel updates; no separate handshake.

import { askMock, askLocal, askAnthropic, askOpenAI } from "./agent.js";
import * as Y from "yjs";

// Stable hash → integer. djb2 / x31 mix; collisions don't matter
// because we only mod by a small N.
function hashString(s) {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = ((h << 5) - h + s.charCodeAt(i)) | 0;
  return Math.abs(h);
}

function assignClientId(leafId, clientIds) {
  if (clientIds.length === 0) return null;
  const sorted = [...clientIds].sort((a, b) => a - b);
  return sorted[hashString(leafId) % sorted.length];
}

// Render a prompt_template by substituting {channelName} → channel value.
function renderTemplate(template, inputs) {
  if (!template) return "";
  return template.replace(/\{(\w+)\}/g, (_, key) =>
    inputs[key] !== undefined ? String(inputs[key]) : `{${key}}`
  );
}

// Built-in reducers (Model B `executor_registered` registry).
const BUILTIN_REDUCERS = {
  // Pretty markdown report stitching `summary` + `issues`. Used by
  // the cowork_review fixture.
  "neoprotocol.builtin.markdown_report"(inputs, ctx) {
    const id = ctx.taskId.slice(0, 8);
    const ls = (leafId) => ctx.leafStatus(leafId);
    const stat = (s) => s
      ? `peer client=${s.clientId} via ${s.agentId}, ${s.duration_ms ?? "?"} ms`
      : "(no status)";
    const block = (label, text, leaf) =>
      [`**${label}** — _${stat(ls(leaf))}_:`, ``, String(text || "(empty)").trim(), ``].join("\n");
    return [
      `## Cowork review report (task ${id}, SPEC §17.8 fan-out)`,
      ``,
      block("Summary", inputs.summary, "summarize"),
      block("Issues",  inputs.issues,  "find_issues"),
      `---`,
      `_Generated by NeoProtocol §17.8 multi-host fan-out — leaves were`,
      `assigned to different Coworkers and executed independently with`,
      `each peer's chosen agent. The reducer was deterministic; the`,
      `report bytes are attributed in §17.5 metadata to the peer that ran it._`,
      ``
    ].join("\n");
  }
};

// ------------------------------------------------------------------
// TaskRunner — one per Coworker. Subscribes to Y.Doc maps, evaluates
// what's runnable on each change, executes assigned leaves, and
// finalizes the report.
// ------------------------------------------------------------------

export class TaskRunner extends EventTarget {
  constructor({ ws, ourClientId, getAgentSelection, log }) {
    super();
    this.ws = ws;
    this.ourClientId = ourClientId;
    this.getAgentSelection = getAgentSelection;
    this.log = log || (() => {});

    this.taskMap       = ws.doc.getMap("task");
    this.channelsMap   = ws.doc.getMap("channels");
    this.leafStatusMap = ws.doc.getMap("leaf_status");

    // We use a single observer per map. Y.js will fire on local
    // transactions too, but we re-evaluate idempotently — running an
    // already-done leaf is a no-op.
    this.taskMap.observe(() => this._evaluate());
    this.channelsMap.observe(() => this._evaluate());
    this.leafStatusMap.observe(() => this._evaluate());

    // If the doc already has an offer when we attach (we joined a
    // room mid-task), kick the evaluator immediately.
    queueMicrotask(() => this._evaluate());
  }

  // List of all known clientIds in the room — both peers' Y.js
  // awareness states. We sort and hash leaf IDs against this list to
  // assign work race-free.
  _allClientIds() {
    if (!this.ws.awareness) return [this.ourClientId];
    const ids = [...this.ws.awareness.getStates().keys()];
    if (!ids.includes(this.ourClientId)) ids.push(this.ourClientId);
    return ids;
  }

  // Initiator path — POST the user's prompt to Originator, receive
  // the Task Offer, broadcast it. Only one peer should call this
  // (the one whose user typed the prompt). The OTHER peer learns of
  // the offer via Y.js Map sync and starts evaluating its assigned
  // leaves automatically.
  async runFromPrompt({ prompt, originatorUrl }) {
    if (this.taskMap.get("status") === "running") {
      throw new Error("a task is already running; reset first");
    }
    this.log(`task: POST /tasks "${prompt.slice(0, 60)}…"`);
    const r = await fetch(`${originatorUrl}/tasks`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ prompt })
    });
    if (!r.ok) {
      const err = await r.text();
      throw new Error(`Originator ${r.status}: ${err.slice(0, 240)}`);
    }
    const offer = await r.json();
    this.log(`task: offer ${offer.task.id.slice(0, 8)} (${offer.graph.nodes.length} nodes, ${offer.graph.edges.length} edges)`);

    // Broadcast everything in one Y.js transaction so peers see a
    // consistent snapshot.
    this.ws.doc.transact(() => {
      this.taskMap.set("offer", offer);
      this.taskMap.set("status", "running");
      this.taskMap.set("started_at", Date.now());
      this.taskMap.set("initiator_client_id", this.ourClientId);
      // Seed the `document` channel with the current workspace text.
      this.channelsMap.set("document", this.ws.yText.toString());
    });

    return offer;
  }

  reset() {
    this.ws.doc.transact(() => {
      for (const k of [...this.taskMap.keys()])       this.taskMap.delete(k);
      for (const k of [...this.channelsMap.keys()])   this.channelsMap.delete(k);
      for (const k of [...this.leafStatusMap.keys()]) this.leafStatusMap.delete(k);
    });
    this.log(`task: reset`);
  }

  // Public read for UI: { offer, status, leafStatus, channels, assignments }
  snapshot() {
    const offer = this.taskMap.get("offer");
    if (!offer) return null;
    const clientIds = this._allClientIds();
    const assignments = {};
    for (const node of offer.graph.nodes) {
      assignments[node.id] = assignClientId(node.id, clientIds);
    }
    const leafStatus = {};
    for (const node of offer.graph.nodes) {
      leafStatus[node.id] = this.leafStatusMap.get(node.id) || { state: "pending" };
    }
    const channels = {};
    for (const k of this.channelsMap.keys()) {
      const v = this.channelsMap.get(k);
      channels[k] = typeof v === "string" ? v : JSON.stringify(v);
    }
    return {
      offer,
      status: this.taskMap.get("status"),
      assignments,
      leafStatus,
      channels,
      ourClientId: this.ourClientId,
      clientIds
    };
  }

  // ----- internals -----

  _evaluate() {
    const offer = this.taskMap.get("offer");
    if (!offer) return;
    const status = this.taskMap.get("status");
    if (status !== "running") return;

    const clientIds = this._allClientIds();

    for (const node of offer.graph.nodes) {
      const cur = this.leafStatusMap.get(node.id);
      if (cur && (cur.state === "running" || cur.state === "done")) continue;
      const assignedTo = assignClientId(node.id, clientIds);
      if (assignedTo !== this.ourClientId) continue;
      const reads = node.reads || [];
      const allReady = reads.every((ch) => this.channelsMap.has(ch));
      if (!allReady) continue;
      // Fire and forget — the await happens inside _runNode and
      // mutates Y.js maps which re-trigger _evaluate idempotently.
      this._runNode(node).catch((e) =>
        this.log(`task: node ${node.id} crashed: ${e.message}`)
      );
    }

    // Completion check — every node is done.
    const allDone = offer.graph.nodes.every((n) =>
      this.leafStatusMap.get(n.id)?.state === "done");
    if (allDone) {
      this._finalize(offer);
    }
  }

  async _runNode(node) {
    const startedAt = Date.now();
    const sel = this.getAgentSelection();
    this.ws.doc.transact(() => {
      this.leafStatusMap.set(node.id, {
        state: "running",
        clientId: this.ourClientId,
        agentId: sel.agentId,
        started_at: startedAt
      });
    });
    this.log(`task: ${node.id} (${node.kind}) running here`);

    try {
      const inputs = {};
      for (const ch of node.reads || []) inputs[ch] = this.channelsMap.get(ch);
      const output = await this._executeNode(node, inputs, sel);

      this.ws.doc.transact(() => {
        for (const w of node.writes || []) this.channelsMap.set(w, output);
        this.leafStatusMap.set(node.id, {
          state: "done",
          clientId: this.ourClientId,
          agentId: sel.agentId,
          started_at: startedAt,
          completed_at: Date.now(),
          duration_ms: Date.now() - startedAt
        });
      });
      this.log(`task: ${node.id} done (${Date.now() - startedAt} ms)`);
    } catch (e) {
      this.ws.doc.transact(() => {
        this.leafStatusMap.set(node.id, {
          state: "failed",
          clientId: this.ourClientId,
          error: e.message,
          started_at: startedAt,
          completed_at: Date.now()
        });
      });
      this.log(`task: ${node.id} FAILED — ${e.message}`);
      throw e;
    }
  }

  async _executeNode(node, inputs, sel) {
    if (node.kind === "leaf") {
      const tmpl = node.implementation?.prompt_template || "{document}";
      const filled = renderTemplate(tmpl, inputs);
      // Reuse the existing agent backends. We pass the prompt as the
      // "request" and the document channel as the working document.
      const document = inputs.document || "";
      const promptOnly = filled.replace(document, "").trim() || filled;
      const r = await this._runAgent({ prompt: promptOnly, document, sel });
      // For text-out leaves, we treat the agent's reasoning OR the
      // newDocument trailing portion as the channel value. The mock
      // and local agents tend to put the salient text in newDocument.
      const out = r.newDocument || r.reasoning || "";
      // Strip leading copy of the document if the agent echoed it.
      if (out.startsWith(document)) return out.slice(document.length).trim();
      return out.trim();
    }
    if (node.kind === "reducer") {
      const nm = node.implementation?.node_name;
      const fn = BUILTIN_REDUCERS[nm];
      if (!fn) throw new Error(`unregistered reducer: ${nm}`);
      const ctx = {
        taskId: this.taskMap.get("offer").task.id,
        leafStatus: (id) => this.leafStatusMap.get(id)
      };
      return fn(inputs, ctx);
    }
    throw new Error(`unknown node kind: ${node.kind}`);
  }

  async _runAgent({ prompt, document, sel }) {
    if (sel.agentId === "mock")      return askMock({ prompt, document });
    if (sel.agentId === "local")     return askLocal({ modelId: sel.modelId, prompt, document });
    if (sel.agentId === "openai")    return askOpenAI({ apiKey: sel.apiKey, prompt, document });
    if (sel.agentId === "anthropic") return askAnthropic({ apiKey: sel.apiKey, prompt, document });
    throw new Error(`unknown agent mode: ${sel.agentId}`);
  }

  _finalize(offer) {
    if (this.taskMap.get("status") !== "running") return;
    const report = this.channelsMap.get("report");
    if (!report) return;
    // Only the peer that ran the reducer prepends to the workspace
    // doc — they are the natural bytes-author for §17.5 attribution.
    const reducerNode = offer.graph.nodes.find((n) => n.kind === "reducer");
    const reducerStat = reducerNode ? this.leafStatusMap.get(reducerNode.id) : null;
    const iAmReducer = reducerStat && reducerStat.clientId === this.ourClientId;

    this.ws.doc.transact(() => this.taskMap.set("status", "done"));
    this.log(`task: ${offer.task.id.slice(0, 8)} all nodes done`);

    if (iAmReducer) {
      const cur = this.ws.yText.toString();
      const newText = `${report}\n\n${cur}`;
      this.ws.applyAgentEdit({
        newText,
        agentId: "cowork-task",
        peerId:  String(this.ourClientId)
      });
      this.log(`task: report prepended to workspace (I ran the reducer)`);
    }
    this.dispatchEvent(new CustomEvent("task-complete", { detail: { offer } }));
  }
}
